services:
  tamyez-app-prod:
    build: 
      context: .
      target: prod
    
    extra_hosts:
      - "host.docker.internal:host-gateway"
     
    container_name: tamyez-app-prod-cont
    env_file:
      - ./config/.env.production
    
    ports:
      - "4001:3002"
    restart: always